### ISSUE TITLE
Full-screen Mode

### ISSUE THREAD

**Issue by getrdone** [torvic9/virtualbox#2]
First - thanks for creating the i3wm patch, it's much appreciated!

The issue I'm having, is when I try to use full-screen mode, the Guest OS window disappears and all I can see is my desktop wallpaper and the VBox User Interface Mini ToolBar.

I'm currently running `manjaro 18.04` and kernel `4.19.32-1`

Screenshot
![vbox_full-screen-issue-02](https://user-images.githubusercontent.com/31090010/55920869-5087eb00-5baf-11e9-987a-29e7a5964b8c.png)

**Comment by torvic9** [comment]
Hello, a few things:
1. I didn't create the patch. I pulled it from AUR.
2. I haven't started i3wm in over 6 months
3. I never use fullscreen mode in VBox.
I'm afraid, I cannot help you.

**Comment by getrdone** [comment]
Thanks for the the clarification.

I did find a workaround solution, but not a permanent fix. If you don't mind, I will post and link to it here just for posterity sake.

The Workaround: https://github.com/i3/i3/issues/2324#issuecomment-216045371

> for fullscreen in virtualbox make sure that in the VM options you **don't** have the mini-toolbar set to show in fullscreen/seamless (go in the VM settings, 'user interface', remove the checkbox) at least with my virtualbox version I have to do that otherwise fullscreen does not work
